<?php
namespace backend\models;

use Yii;

/**
 * This is the model class for table "qinlian_petition".
 *
 * @property integer $id
 * @property string $number
 * @property string $receipt_time
 * @property string $turn_number
 * @property string $transfer_organ
 * @property string $name_report
 * @property string $name_reported
 * @property string $political_appearance
 * @property string $unit_job
 * @property string $duty_job
 * @property string $rank_job
 * @property string $main_issues
 * @property string $issues_properties
 * @property string $petition_office_opinion
 * @property string $superior_guidance_opinion
 * @property string $lu_clerk_opinion
 * @property string $major_leadership_approval_opinion
 * @property string $charge_leadership_approval_opinion
 * @property string $host_department
 * @property string $handle_results
 * @property string $heavy_letter
 * @property string $unit_responsibility
 * @property string $approval_time
 * @property integer $approval_status
 * @property integer $del_status
 * @property string $create_date
 * @property string $update_time
 */
class QinlianPetition extends \backend\models\BaseModel
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'qinlian_petition';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['receipt_time', 'approval_time', 'create_date', 'update_time', 'disposal_year'], 'safe'],
            [['volume_number', 'approval_status', 'del_status'], 'integer'],
            [['number', 'turn_number', 'transfer_organ', 'name_report', 'name_reported', 'political_appearance', 'unit_job', 'duty_job', 'rank_job', 'host_department', 'unit_responsibility', 'is_thread_disposal', 'disposal_method'], 'string', 'max' => 25],
            [['main_issues', 'handle_results'], 'string', 'max' => 500],
            [['issues_properties'], 'string', 'max' => 200],
            [['petition_office_opinion', 'superior_guidance_opinion', 'lu_clerk_opinion', 'major_leadership_approval_opinion', 'charge_leadership_approval_opinion'], 'string', 'max' => 100],
            [['heavy_letter'], 'string', 'max' => 20],
            [['id_card'], 'string', 'max' => 18]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'number' => '档案号',
            'receipt_time' => '收件时间',
            'turn_number' => '转来编号',
            'transfer_organ' => '转来机关',
            'name_report' => '举报人姓名',
            'name_reported' => '被检举人姓名',
            'political_appearance' => '政治面貌',
            'unit_job' => '单位',
            'duty_job' => '职务',
            'rank_job' => '职级',
            'main_issues' => '反映的主要问题',
            'issues_properties' => '问题属性',
            'petition_office_opinion' => '信访室意见',
            'superior_guidance_opinion' => '上级领导意见',
            'lu_clerk_opinion' => '路书记批示意见',
            'major_leadership_approval_opinion' => '主要领导审批意见',
            'charge_leadership_approval_opinion' => '分管领导审批意见',
            'host_department' => '承办科室',
            'handle_results' => '办理结果',
            'heavy_letter' => '重信',
            'unit_responsibility' => '责任单位',
            'approval_time' => '审批时间',
            'approval_status' => '审批状态',
            'is_thread_disposal' => '作为线索处置',
            'disposal_method' => '处置方式',
            'volume_number' => '卷本数',
            'id_card' => '身份证号',
            'disposal_year' => '处置年份',
            'del_status' => '删除状态',
            'create_date' => '创建时间',
            'update_time' => '更新时间',
        ];
    }

  /**
     * 返回数据库字段信息，仅在生成CRUD时使用，如不需要生成CRUD，请注释或删除该getTableColumnInfo()代码
     * COLUMN_COMMENT可用key如下:
     * label - 显示的label
     * inputType 控件类型, 暂时只支持text,hidden  // select,checkbox,radio,file,password,
     * isEdit   是否允许编辑，如果允许编辑将在添加和修改时输入
     * isSearch 是否允许搜索
     * isDisplay 是否在列表中显示
     * isOrder 是否排序
     * udc - udc code，inputtype为select,checkbox,radio三个值时用到。
     * 特别字段：
     * id：主键。必须含有主键，统一都是id
     * create_date: 创建时间。生成的代码自动赋值
     * update_date: 修改时间。生成的代码自动赋值
     */
    public function getTableColumnInfo(){
        return array(
        'id' => array(
                        'name' => 'id',
                        'allowNull' => false,
//                         'autoIncrement' => true,
//                         'comment' => 'ID',
//                         'dbType' => "mediumint(8) unsigned",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => true,
                        'phpType' => 'integer',
                        'precision' => '8',
                        'scale' => '',
                        'size' => '8',
                        'type' => 'integer',
                        'unsigned' => true,
                        'label'=>$this->getAttributeLabel('id'),
                        'inputType' => 'hidden',
                        'isEdit' => true,
                        'isSearch' => true,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'number' => array(
                        'name' => 'number',
                        'allowNull' => false,
//                         'autoIncrement' => false,
//                         'comment' => '编号',
//                         'dbType' => "varchar(25)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '25',
                        'scale' => '',
                        'size' => '25',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('number'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'receipt_time' => array(
                        'name' => 'receipt_time',
                        'allowNull' => false,
//                         'autoIncrement' => false,
//                         'comment' => '收件时间',
//                         'dbType' => "timestamp",
                        'defaultValue' => 'CURRENT_TIMESTAMP',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '',
                        'scale' => '',
                        'size' => '',
                        'type' => 'timestamp',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('receipt_time'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'turn_number' => array(
                        'name' => 'turn_number',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '转来编号',
//                         'dbType' => "varchar(25)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '25',
                        'scale' => '',
                        'size' => '25',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('turn_number'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'transfer_organ' => array(
                        'name' => 'transfer_organ',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '转来机关',
//                         'dbType' => "varchar(25)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '25',
                        'scale' => '',
                        'size' => '25',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('transfer_organ'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'name_report' => array(
                        'name' => 'name_report',
                        'allowNull' => false,
//                         'autoIncrement' => false,
//                         'comment' => '举报人姓名',
//                         'dbType' => "varchar(25)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '25',
                        'scale' => '',
                        'size' => '25',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('name_report'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'name_reported' => array(
                        'name' => 'name_reported',
                        'allowNull' => false,
//                         'autoIncrement' => false,
//                         'comment' => '被检举人姓名',
//                         'dbType' => "varchar(25)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '25',
                        'scale' => '',
                        'size' => '25',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('name_reported'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'political_appearance' => array(
                        'name' => 'political_appearance',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '政治面貌(0 未知，1 党员，2 非党员)',
//                         'dbType' => "tinyint(1)",
                        'defaultValue' => '未知',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '25',
                        'scale' => '',
                        'size' => '25',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('political_appearance'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'unit_job' => array(
                        'name' => 'unit_job',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '单位',
//                         'dbType' => "varchar(25)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '25',
                        'scale' => '',
                        'size' => '25',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('unit_job'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'duty_job' => array(
                        'name' => 'duty_job',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '职务（0 未知，1 一般干部，2 乡科级，3 农村干部 ，4  股级， 5，农村其他人员）',
//                         'dbType' => "tinyint(1)",
                        'defaultValue' => '未知',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '25',
                        'scale' => '',
                        'size' => '25',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('duty_job'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'rank_job' => array(
                        'name' => 'rank_job',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '职级',
//                         'dbType' => "varchar(25)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '25',
                        'scale' => '',
                        'size' => '25',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('rank_job'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'main_issues' => array(
                        'name' => 'main_issues',
                        'allowNull' => false,
//                         'autoIncrement' => false,
//                         'comment' => '反映的主要问题',
//                         'dbType' => "varchar(500)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '500',
                        'scale' => '',
                        'size' => '500',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('main_issues'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'issues_properties' => array(
                        'name' => 'issues_properties',
                        'allowNull' => false,
//                         'autoIncrement' => false,
//                         'comment' => '问题属性',
//                         'dbType' => "varchar(200)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '200',
                        'scale' => '',
                        'size' => '200',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('issues_properties'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'petition_office_opinion' => array(
                        'name' => 'petition_office_opinion',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '信访室意见',
//                         'dbType' => "varchar(100)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '100',
                        'scale' => '',
                        'size' => '100',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('petition_office_opinion'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'superior_guidance_opinion' => array(
                        'name' => 'superior_guidance_opinion',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '上级领导意见',
//                         'dbType' => "varchar(100)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '100',
                        'scale' => '',
                        'size' => '100',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('superior_guidance_opinion'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'lu_clerk_opinion' => array(
                        'name' => 'lu_clerk_opinion',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '路书记批示意见',
//                         'dbType' => "varchar(100)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '100',
                        'scale' => '',
                        'size' => '100',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('lu_clerk_opinion'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'major_leadership_approval_opinion' => array(
                        'name' => 'major_leadership_approval_opinion',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '主要领导审批意见',
//                         'dbType' => "varchar(100)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '100',
                        'scale' => '',
                        'size' => '100',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('major_leadership_approval_opinion'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'charge_leadership_approval_opinion' => array(
                        'name' => 'charge_leadership_approval_opinion',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '分管领导审批意见',
//                         'dbType' => "varchar(100)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '100',
                        'scale' => '',
                        'size' => '100',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('charge_leadership_approval_opinion'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'host_department' => array(
                        'name' => 'host_department',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '承办科室',
//                         'dbType' => "varchar(25)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '25',
                        'scale' => '',
                        'size' => '25',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('host_department'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'handle_results' => array(
                        'name' => 'handle_results',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '办理结果',
//                         'dbType' => "varchar(500)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '500',
                        'scale' => '',
                        'size' => '500',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('handle_results'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'heavy_letter' => array(
                        'name' => 'heavy_letter',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '重信',
//                         'dbType' => "varchar(20)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '20',
                        'scale' => '',
                        'size' => '20',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('heavy_letter'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'unit_responsibility' => array(
                        'name' => 'unit_responsibility',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '责任单位',
//                         'dbType' => "varchar(25)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '25',
                        'scale' => '',
                        'size' => '25',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('unit_responsibility'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'approval_time' => array(
                        'name' => 'approval_time',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '审批时间',
//                         'dbType' => "timestamp",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '',
                        'scale' => '',
                        'size' => '',
                        'type' => 'timestamp',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('approval_time'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'approval_status' => array(
                        'name' => 'approval_status',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '审批状态',
//                         'dbType' => "int(1)",
                        'defaultValue' => '0',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'integer',
                        'precision' => '1',
                        'scale' => '',
                        'size' => '1',
                        'type' => 'integer',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('approval_status'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),

		'is_thread_disposal' => array(
            'name' => 'is_thread_disposal',
            'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '作为线索处置',
//                         'dbType' => "varchar(25)",
            'defaultValue' => '',
            'enumValues' => null,
            'isPrimaryKey' => false,
            'phpType' => 'string',
            'precision' => '25',
            'scale' => '',
            'size' => '25',
            'type' => 'string',
            'unsigned' => false,
            'label'=>$this->getAttributeLabel('is_thread_disposal'),
            'inputType' => 'text',
            'isEdit' => true,
            'isSearch' => false,
            'isDisplay' => true,
            'isSort' => true,
//                         'udc'=>'',
            ),

		'disposal_method' => array(
            'name' => 'disposal_method',
            'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '处置方式',
//                         'dbType' => "varchar(25)",
            'defaultValue' => '',
            'enumValues' => null,
            'isPrimaryKey' => false,
            'phpType' => 'string',
            'precision' => '25',
            'scale' => '',
            'size' => '25',
            'type' => 'string',
            'unsigned' => false,
            'label'=>$this->getAttributeLabel('disposal_method'),
            'inputType' => 'text',
            'isEdit' => true,
            'isSearch' => false,
            'isDisplay' => true,
            'isSort' => true,
//                         'udc'=>'',
        ),

		'volume_number' => array(
            'name' => 'volume_number',
            'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '卷本数',
//                         'dbType' => "int(1)",
            'defaultValue' => '0',
            'enumValues' => null,
            'isPrimaryKey' => false,
            'phpType' => 'integer',
            'precision' => '3',
            'scale' => '',
            'size' => '3',
            'type' => 'integer',
            'unsigned' => false,
            'label'=>$this->getAttributeLabel('volume_number'),
            'inputType' => 'text',
            'isEdit' => true,
            'isSearch' => false,
            'isDisplay' => true,
            'isSort' => true,
//                         'udc'=>'',
        ),

        'id_card' => array(
            'name' => 'id_card',
            'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '身份证号',
//                         'dbType' => "varchar(25)",
            'defaultValue' => '',
            'enumValues' => null,
            'isPrimaryKey' => false,
            'phpType' => 'string',
            'precision' => '18',
            'scale' => '',
            'size' => '18',
            'type' => 'string',
            'unsigned' => false,
            'label'=>$this->getAttributeLabel('id_card'),
            'inputType' => 'text',
            'isEdit' => true,
            'isSearch' => false,
            'isDisplay' => true,
            'isSort' => true,
//                         'udc'=>'',
        ),

		'disposal_year' => array(
            'name' => 'disposal_year',
            'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '处置年份',
//                         'dbType' => "date",
            'defaultValue' => '',
            'enumValues' => null,
            'isPrimaryKey' => false,
            'phpType' => 'string',
            'precision' => '',
            'scale' => '',
            'size' => '',
            'type' => 'date',
            'unsigned' => false,
            'label'=>$this->getAttributeLabel('disposal_year'),
            'inputType' => 'text',
            'isEdit' => true,
            'isSearch' => false,
            'isDisplay' => true,
            'isSort' => true,
//                         'udc'=>'',
        ),

		'del_status' => array(
                        'name' => 'del_status',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '删除状态',
//                         'dbType' => "int(1)",
                        'defaultValue' => '0',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'integer',
                        'precision' => '1',
                        'scale' => '',
                        'size' => '1',
                        'type' => 'integer',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('del_status'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'create_date' => array(
                        'name' => 'create_date',
                        'allowNull' => false,
//                         'autoIncrement' => false,
//                         'comment' => '创建时间',
//                         'dbType' => "timestamp",
                        'defaultValue' => 'CURRENT_TIMESTAMP',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '',
                        'scale' => '',
                        'size' => '',
                        'type' => 'timestamp',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('create_date'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'update_time' => array(
                        'name' => 'update_time',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '更新时间',
//                         'dbType' => "timestamp",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '',
                        'scale' => '',
                        'size' => '',
                        'type' => 'timestamp',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('update_time'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		        );
        
    }
 
}
