<?php
namespace backend\models;

use Yii;

/**
 * This is the model class for table "qinlian_thread".
 *
 * @property integer $id
 * @property integer $is_nuit
 * @property string $nuit_name
 * @property string $nuit_code
 * @property string $statistical_identification
 * @property string $clue_code
 * @property string $personnel_code
 * @property string $person_reflected
 * @property string $duty_job
 * @property integer $is_supervises_object
 * @property string $rank_job
 * @property string $recovers_economic_loss
 * @property string $collects_amount
 * @property string $handling_organ
 * @property string $main_problem_clues
 * @property string $remarks
 * @property string $nation
 * @property string $date_birth
 * @property string $cpc
 * @property string $cppcc
 * @property string $disposal_report
 * @property string $time_joining_party
 * @property string $authority_management
 * @property string $acceptance_time
 * @property string $approval_time_one
 * @property string $statistical_time_one
 * @property string $one_level_first
 * @property string $one_level_second
 * @property string $approval_time_two
 * @property string $statistical_time_two
 * @property string $two_level_first
 * @property string $two_level_second
 * @property string $approval_time_three
 * @property string $statistical_time_three
 * @property string $three_level_first
 * @property string $three_level_second
 * @property string $cases_source
 * @property string $disciplinary_offence
 * @property integer $is_checking_me
 * @property integer $is_party
 * @property string $secondary_class_objects
 * @property integer $is_supervisory_objects
 * @property string $no_secondary_class_objects
 * @property string $official_offences
 * @property string $other_offences
 * @property string $organization_measure_time
 * @property string $superiors_assigned
 * @property string $department_charge
 * @property integer $del_status
 * @property string $create_date
 * @property string $update_time
 */
class QinlianThread extends \backend\models\BaseModel
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'qinlian_thread';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['date_birth', 'time_joining_party', 'approval_time_one', 'statistical_time_one', 'approval_time_two', 'statistical_time_two', 'approval_time_three', 'statistical_time_three', 'organization_measure_time', 'create_date', 'update_time'], 'safe'],
            [['del_status'], 'integer'],
            [['is_nuit', 'is_supervises_object', 'is_checking_me', 'is_party'], 'string', 'max' => 25],
            [['nuit_name', 'nuit_code', 'statistical_identification', 'clue_code', 'personnel_code', 'person_reflected', 'duty_job', 'rank_job', 'recovers_economic_loss', 'collects_amount', 'handling_organ', 'nation', 'cpc', 'cppcc', 'authority_management', 'acceptance_time', 'one_level_first', 'one_level_second', 'two_level_first', 'two_level_second', 'three_level_first', 'three_level_second', 'secondary_class_objects', 'no_secondary_class_objects', 'superiors_assigned', 'department_charge'], 'string', 'max' => 25],
            [['main_problem_clues', 'disposal_report'], 'string', 'max' => 500],
            [['remarks', 'cases_source', 'disciplinary_offence', 'official_offences', 'other_offences'], 'string', 'max' => 100],
            [['is_supervisory_objects'], 'string', 'max' => 25]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'is_nuit' => '是否单位',
            'nuit_name' => '填报单位名称',
            'nuit_code' => '填报单位代码',
            'statistical_identification' => '统计标识',
            'clue_code' => '线索编码',
            'personnel_code' => '人员编码',
            'person_reflected' => '被反映人',
            'duty_job' => '工作单位及职务',
            'is_supervises_object' => '是否国家监察对象',
            'rank_job' => '职级',
            'recovers_economic_loss' => '挽回经济损失',
            'collects_amount' => '收缴涉案金额',
            'handling_organ' => '办理机关',
            'main_problem_clues' => '主要问题线索',
            'remarks' => '备注',
            'nation' => '民族',
            'date_birth' => '出生年月',
            'cpc' => '人大代表',
            'cppcc' => '政协委员',
            'disposal_report' => '处置情况报告',
            'time_joining_party' => '入党时间',
            'authority_management' => '干部管理权限',
            'acceptance_time' => '受理时间',
            'approval_time_one' => '处置方式1批准时间',
            'statistical_time_one' => '处置方式1统计时间',
            'one_level_first' => '处置方式1一级',
            'one_level_second' => '处置方式1二级',
            'approval_time_two' => '处置方式2批准时间',
            'statistical_time_two' => '处置方式2统计时间',
            'two_level_first' => '处置方式2一级',
            'two_level_second' => '处置方式2二级',
            'approval_time_three' => '处置方式3批准时间',
            'statistical_time_three' => '处置方式3统计时间',
            'three_level_first' => '处置方式3一级',
            'three_level_second' => '处置方式3二级',
            'cases_source' => '案件来源',
            'disciplinary_offence' => '违纪行为',
            'is_checking_me' => '是否与本人核实',
            'is_party' => '是否党员',
            'secondary_class_objects' => '监察对象二级分类',
            'is_supervisory_objects' => '是否非党员非监察对象',
            'no_secondary_class_objects' => '非党员非监察对象二级分类',
            'official_offences' => '职务犯罪行为',
            'other_offences' => '其他违犯罪行为',
            'organization_measure_time' => '组织措施统计时间',
            'superiors_assigned' => '上级交办',
            'department_charge' => '分管科室',
            'del_status' => '删除状态',
            'create_date' => '创建时间',
            'update_time' => '更新时间',
        ];
    }

  /**
     * 返回数据库字段信息，仅在生成CRUD时使用，如不需要生成CRUD，请注释或删除该getTableColumnInfo()代码
     * COLUMN_COMMENT可用key如下:
     * label - 显示的label
     * inputType 控件类型, 暂时只支持text,hidden  // select,checkbox,radio,file,password,
     * isEdit   是否允许编辑，如果允许编辑将在添加和修改时输入
     * isSearch 是否允许搜索
     * isDisplay 是否在列表中显示
     * isOrder 是否排序
     * udc - udc code，inputtype为select,checkbox,radio三个值时用到。
     * 特别字段：
     * id：主键。必须含有主键，统一都是id
     * create_date: 创建时间。生成的代码自动赋值
     * update_date: 修改时间。生成的代码自动赋值
     */
    public function getTableColumnInfo(){
        return array(
        'id' => array(
                        'name' => 'id',
                        'allowNull' => false,
//                         'autoIncrement' => true,
//                         'comment' => 'ID',
//                         'dbType' => "mediumint(8) unsigned",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => true,
                        'phpType' => 'integer',
                        'precision' => '8',
                        'scale' => '',
                        'size' => '8',
                        'type' => 'integer',
                        'unsigned' => true,
                        'label'=>$this->getAttributeLabel('id'),
                        'inputType' => 'hidden',
                        'isEdit' => true,
                        'isSearch' => true,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'is_nuit' => array(
                        'name' => 'is_nuit',
                        'allowNull' => false,
//                         'autoIncrement' => false,
//                         'comment' => '是否单位(0 未知，1 是，2 否)',
//                         'dbType' => "tinyint(1)",
                        'defaultValue' => '0',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '25',
                        'scale' => '',
                        'size' => '25',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('is_nuit'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'nuit_name' => array(
                        'name' => 'nuit_name',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '填报单位名称',
//                         'dbType' => "varchar(25)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '25',
                        'scale' => '',
                        'size' => '25',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('nuit_name'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'nuit_code' => array(
                        'name' => 'nuit_code',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '填报单位代码',
//                         'dbType' => "varchar(25)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '25',
                        'scale' => '',
                        'size' => '25',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('nuit_code'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'statistical_identification' => array(
                        'name' => 'statistical_identification',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '统计标识',
//                         'dbType' => "varchar(25)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '25',
                        'scale' => '',
                        'size' => '25',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('statistical_identification'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'clue_code' => array(
                        'name' => 'clue_code',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '线索编码',
//                         'dbType' => "varchar(25)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '25',
                        'scale' => '',
                        'size' => '25',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('clue_code'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'personnel_code' => array(
                        'name' => 'personnel_code',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '人员编码',
//                         'dbType' => "varchar(25)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '25',
                        'scale' => '',
                        'size' => '25',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('personnel_code'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'person_reflected' => array(
                        'name' => 'person_reflected',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '被反映人',
//                         'dbType' => "varchar(25)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '25',
                        'scale' => '',
                        'size' => '25',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('person_reflected'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'duty_job' => array(
                        'name' => 'duty_job',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '工作单位及职务',
//                         'dbType' => "varchar(25)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '25',
                        'scale' => '',
                        'size' => '25',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('duty_job'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'is_supervises_object' => array(
                        'name' => 'is_supervises_object',
                        'allowNull' => false,
//                         'autoIncrement' => false,
//                         'comment' => '是否国家监察对象(0 未知，1 是，2 否)',
//                         'dbType' => "tinyint(1)",
                        'defaultValue' => '0',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '25',
                        'scale' => '',
                        'size' => '25',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('is_supervises_object'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'rank_job' => array(
                        'name' => 'rank_job',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '职级',
//                         'dbType' => "varchar(25)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '25',
                        'scale' => '',
                        'size' => '25',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('rank_job'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'recovers_economic_loss' => array(
                        'name' => 'recovers_economic_loss',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '挽回经济损失',
//                         'dbType' => "varchar(25)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '25',
                        'scale' => '',
                        'size' => '25',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('recovers_economic_loss'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'collects_amount' => array(
                        'name' => 'collects_amount',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '收缴涉案金额',
//                         'dbType' => "varchar(25)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '25',
                        'scale' => '',
                        'size' => '25',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('collects_amount'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'handling_organ' => array(
                        'name' => 'handling_organ',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '办理机关',
//                         'dbType' => "varchar(25)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '25',
                        'scale' => '',
                        'size' => '25',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('handling_organ'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'main_problem_clues' => array(
                        'name' => 'main_problem_clues',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '主要问题线索',
//                         'dbType' => "varchar(500)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '500',
                        'scale' => '',
                        'size' => '500',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('main_problem_clues'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'remarks' => array(
                        'name' => 'remarks',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '备注',
//                         'dbType' => "varchar(100)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '100',
                        'scale' => '',
                        'size' => '100',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('remarks'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'nation' => array(
                        'name' => 'nation',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '民族',
//                         'dbType' => "varchar(25)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '25',
                        'scale' => '',
                        'size' => '25',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('nation'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'date_birth' => array(
                        'name' => 'date_birth',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '出生年月',
//                         'dbType' => "date",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '',
                        'scale' => '',
                        'size' => '',
                        'type' => 'date',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('date_birth'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'cpc' => array(
                        'name' => 'cpc',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '人大代表',
//                         'dbType' => "varchar(25)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '25',
                        'scale' => '',
                        'size' => '25',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('cpc'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'cppcc' => array(
                        'name' => 'cppcc',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '政协委员',
//                         'dbType' => "varchar(25)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '25',
                        'scale' => '',
                        'size' => '25',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('cppcc'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'disposal_report' => array(
                        'name' => 'disposal_report',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '处置情况报告',
//                         'dbType' => "varchar(500)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '500',
                        'scale' => '',
                        'size' => '500',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('disposal_report'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'time_joining_party' => array(
                        'name' => 'time_joining_party',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '入党时间',
//                         'dbType' => "timestamp",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '',
                        'scale' => '',
                        'size' => '',
                        'type' => 'timestamp',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('time_joining_party'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'authority_management' => array(
                        'name' => 'authority_management',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '干部管理权限',
//                         'dbType' => "varchar(25)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '25',
                        'scale' => '',
                        'size' => '25',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('authority_management'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'acceptance_time' => array(
                        'name' => 'acceptance_time',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '受理时间',
//                         'dbType' => "varchar(25)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '25',
                        'scale' => '',
                        'size' => '25',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('acceptance_time'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'approval_time_one' => array(
                        'name' => 'approval_time_one',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '处置方式1批准时间',
//                         'dbType' => "timestamp",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '',
                        'scale' => '',
                        'size' => '',
                        'type' => 'timestamp',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('approval_time_one'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'statistical_time_one' => array(
                        'name' => 'statistical_time_one',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '处置方式1统计时间',
//                         'dbType' => "timestamp",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '',
                        'scale' => '',
                        'size' => '',
                        'type' => 'timestamp',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('statistical_time_one'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'one_level_first' => array(
                        'name' => 'one_level_first',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '处置方式1一级',
//                         'dbType' => "varchar(25)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '25',
                        'scale' => '',
                        'size' => '25',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('one_level_first'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'one_level_second' => array(
                        'name' => 'one_level_second',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '处置方式1二级',
//                         'dbType' => "varchar(25)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '25',
                        'scale' => '',
                        'size' => '25',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('one_level_second'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'approval_time_two' => array(
                        'name' => 'approval_time_two',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '处置方式2批准时间',
//                         'dbType' => "timestamp",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '',
                        'scale' => '',
                        'size' => '',
                        'type' => 'timestamp',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('approval_time_two'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'statistical_time_two' => array(
                        'name' => 'statistical_time_two',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '处置方式2统计时间',
//                         'dbType' => "timestamp",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '',
                        'scale' => '',
                        'size' => '',
                        'type' => 'timestamp',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('statistical_time_two'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'two_level_first' => array(
                        'name' => 'two_level_first',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '处置方式2一级',
//                         'dbType' => "varchar(25)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '25',
                        'scale' => '',
                        'size' => '25',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('two_level_first'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'two_level_second' => array(
                        'name' => 'two_level_second',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '处置方式2二级',
//                         'dbType' => "varchar(25)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '25',
                        'scale' => '',
                        'size' => '25',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('two_level_second'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'approval_time_three' => array(
                        'name' => 'approval_time_three',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '处置方式3批准时间',
//                         'dbType' => "timestamp",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '',
                        'scale' => '',
                        'size' => '',
                        'type' => 'timestamp',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('approval_time_three'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'statistical_time_three' => array(
                        'name' => 'statistical_time_three',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '处置方式3统计时间',
//                         'dbType' => "timestamp",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '',
                        'scale' => '',
                        'size' => '',
                        'type' => 'timestamp',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('statistical_time_three'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'three_level_first' => array(
                        'name' => 'three_level_first',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '处置方式3一级',
//                         'dbType' => "varchar(25)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '25',
                        'scale' => '',
                        'size' => '25',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('three_level_first'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'three_level_second' => array(
                        'name' => 'three_level_second',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '处置方式3二级',
//                         'dbType' => "varchar(25)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '25',
                        'scale' => '',
                        'size' => '25',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('three_level_second'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'cases_source' => array(
                        'name' => 'cases_source',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '案件来源',
//                         'dbType' => "varchar(100)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '100',
                        'scale' => '',
                        'size' => '100',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('cases_source'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'disciplinary_offence' => array(
                        'name' => 'disciplinary_offence',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '违纪行为',
//                         'dbType' => "varchar(100)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '100',
                        'scale' => '',
                        'size' => '100',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('disciplinary_offence'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'is_checking_me' => array(
                        'name' => 'is_checking_me',
                        'allowNull' => false,
//                         'autoIncrement' => false,
//                         'comment' => '是否与本人核实(0 未知，1 是，2 否)',
//                         'dbType' => "tinyint(1)",
                        'defaultValue' => '0',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '25',
                        'scale' => '',
                        'size' => '25',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('is_checking_me'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'is_party' => array(
                        'name' => 'is_party',
                        'allowNull' => false,
//                         'autoIncrement' => false,
//                         'comment' => '是否党员(0 未知，1 是，2 否)',
//                         'dbType' => "tinyint(1)",
                        'defaultValue' => '0',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '25',
                        'scale' => '',
                        'size' => '25',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('is_party'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'secondary_class_objects' => array(
                        'name' => 'secondary_class_objects',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '监察对象二级分类',
//                         'dbType' => "varchar(25)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '25',
                        'scale' => '',
                        'size' => '25',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('secondary_class_objects'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'is_supervisory_objects' => array(
                        'name' => 'is_supervisory_objects',
                        'allowNull' => false,
//                         'autoIncrement' => false,
//                         'comment' => '是否非党员非监察对象(0 未知，1 是，2 否)',
//                         'dbType' => "tinyint(4)",
                        'defaultValue' => '0',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '25',
                        'scale' => '',
                        'size' => '25',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('is_supervisory_objects'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'no_secondary_class_objects' => array(
                        'name' => 'no_secondary_class_objects',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '非党员非监察对象二级分类',
//                         'dbType' => "varchar(25)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '25',
                        'scale' => '',
                        'size' => '25',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('no_secondary_class_objects'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'official_offences' => array(
                        'name' => 'official_offences',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '职务犯罪行为',
//                         'dbType' => "varchar(100)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '100',
                        'scale' => '',
                        'size' => '100',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('official_offences'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'other_offences' => array(
                        'name' => 'other_offences',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '其他违犯罪行为',
//                         'dbType' => "varchar(100)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '100',
                        'scale' => '',
                        'size' => '100',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('other_offences'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'organization_measure_time' => array(
                        'name' => 'organization_measure_time',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '组织措施统计时间',
//                         'dbType' => "timestamp",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '',
                        'scale' => '',
                        'size' => '',
                        'type' => 'timestamp',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('organization_measure_time'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'superiors_assigned' => array(
                        'name' => 'superiors_assigned',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '上级交办',
//                         'dbType' => "varchar(25)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '25',
                        'scale' => '',
                        'size' => '25',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('superiors_assigned'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'department_charge' => array(
                        'name' => 'department_charge',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '分管科室',
//                         'dbType' => "varchar(25)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '25',
                        'scale' => '',
                        'size' => '25',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('department_charge'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'del_status' => array(
                        'name' => 'del_status',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '删除状态',
//                         'dbType' => "int(1)",
                        'defaultValue' => '0',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'integer',
                        'precision' => '1',
                        'scale' => '',
                        'size' => '1',
                        'type' => 'integer',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('del_status'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'create_date' => array(
                        'name' => 'create_date',
                        'allowNull' => false,
//                         'autoIncrement' => false,
//                         'comment' => '创建时间',
//                         'dbType' => "timestamp",
                        'defaultValue' => 'CURRENT_TIMESTAMP',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '',
                        'scale' => '',
                        'size' => '',
                        'type' => 'timestamp',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('create_date'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'update_time' => array(
                        'name' => 'update_time',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '更新时间',
//                         'dbType' => "timestamp",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '',
                        'scale' => '',
                        'size' => '',
                        'type' => 'timestamp',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('update_time'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		        );
        
    }
 
}
