<?php
namespace backend\models;

use Yii;

/**
 * This is the model class for table "qinlian_challenge".
 *
 * @property integer $id
 * @property string $number
 * @property string $incoming_time
 * @property string $clue_level
 * @property string $clue_category
 * @property string $clue_source
 * @property string $letter_number
 * @property string $signature
 * @property string $leader_instructions
 * @property string $respondent_unit
 * @property string $duty_job
 * @property string $rank_job
 * @property string $main_issues
 * @property string $related_unit
 * @property string $heavy_cases
 * @property string $date_receipt
 * @property string $transfer_organ
 * @property string $results
 * @property string $supervisory_leadership
 * @property string $host_department
 * @property string $progress_case
 * @property string $investigation_disposal
 * @property string $remarks
 * @property integer $number_disposals
 * @property string $organizations_number
 * @property string $first_form
 * @property string $second_form
 * @property string $third_form
 * @property string $fourth_form
 * @property string $approval_time
 * @property integer $approval_status
 * @property integer $del_status
 * @property string $create_date
 * @property string $update_time
 */
class QinlianChallenge extends \backend\models\BaseModel
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'qinlian_challenge';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['incoming_time', 'date_receipt', 'approval_time', 'create_date', 'update_time', 'disposal_year'], 'safe'],
            [['number_disposals', 'volume_number', 'approval_status', 'del_status'], 'integer'],
            [['number', 'clue_level', 'clue_category', 'letter_number', 'leader_instructions', 'respondent_unit', 'duty_job', 'rank_job', 'transfer_organ', 'supervisory_leadership', 'host_department', 'progress_case', 'first_form', 'second_form', 'third_form', 'fourth_form', 'is_thread_disposal', 'disposal_method'], 'string', 'max' => 25],
            [['clue_source', 'related_unit', 'organizations_number'], 'string', 'max' => 100],
            [['signature', 'main_issues', 'heavy_cases', 'results', 'investigation_disposal', 'remarks'], 'string', 'max' => 500],
//            [['number_disposals'], 'string', 'max' => 3],
            [['id_card'], 'string', 'max' => 18]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'number' => '档案号',
            'incoming_time' => '来件时间',
            'clue_level' => '线索级别',
            'clue_category' => '线索类别',
            'clue_source' => '线索来源',
            'letter_number' => '信件编号',
            'signature' => '署名情况',
            'leader_instructions' => '领导批示',
            'respondent_unit' => '被反映人（单位）',
            'duty_job' => '职务',
            'rank_job' => '职级',
            'main_issues' => '反映的主要问题',
            'related_unit' => '涉及单位',
            'heavy_cases' => '重件情况',
            'date_receipt' => '接到日期',
            'transfer_organ' => '处置方式',
            'results' => '要结果情况',
            'supervisory_leadership' => '督办领导',
            'host_department' => '承办科室',
            'progress_case' => '案件进度',
            'investigation_disposal' => '查处情况',
            'remarks' => '备注',
            'number_disposals' => '处分人数',
            'organizations_number' => '问题属性',
            'first_form' => '第一种形态',
            'second_form' => '第二种形态',
            'third_form' => '第三种形态',
            'fourth_form' => '第四种形态',
            'approval_time' => '审批时间',
            'approval_status' => '审批状态',
            'is_thread_disposal' => '作为线索处置',
            'disposal_method' => '处置方式',
            'volume_number' => '卷本数',
            'id_card' => '身份证号',
            'disposal_year' => '处置年份',
            'del_status' => '删除状态',
            'create_date' => '创建时间',
            'update_time' => '更新时间',
        ];
    }

  /**
     * 返回数据库字段信息，仅在生成CRUD时使用，如不需要生成CRUD，请注释或删除该getTableColumnInfo()代码
     * COLUMN_COMMENT可用key如下:
     * label - 显示的label
     * inputType 控件类型, 暂时只支持text,hidden  // select,checkbox,radio,file,password,
     * isEdit   是否允许编辑，如果允许编辑将在添加和修改时输入
     * isSearch 是否允许搜索
     * isDisplay 是否在列表中显示
     * isOrder 是否排序
     * udc - udc code，inputtype为select,checkbox,radio三个值时用到。
     * 特别字段：
     * id：主键。必须含有主键，统一都是id
     * create_date: 创建时间。生成的代码自动赋值
     * update_date: 修改时间。生成的代码自动赋值
     */
    public function getTableColumnInfo(){
        return array(
        'id' => array(
                        'name' => 'id',
                        'allowNull' => false,
//                         'autoIncrement' => true,
//                         'comment' => 'ID',
//                         'dbType' => "mediumint(8) unsigned",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => true,
                        'phpType' => 'integer',
                        'precision' => '8',
                        'scale' => '',
                        'size' => '8',
                        'type' => 'integer',
                        'unsigned' => true,
                        'label'=>$this->getAttributeLabel('id'),
                        'inputType' => 'hidden',
                        'isEdit' => true,
                        'isSearch' => true,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'number' => array(
                        'name' => 'number',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '序号',
//                         'dbType' => "varchar(25)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '25',
                        'scale' => '',
                        'size' => '25',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('number'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'incoming_time' => array(
                        'name' => 'incoming_time',
                        'allowNull' => false,
//                         'autoIncrement' => false,
//                         'comment' => '来件时间',
//                         'dbType' => "timestamp",
                        'defaultValue' => 'CURRENT_TIMESTAMP',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '',
                        'scale' => '',
                        'size' => '',
                        'type' => 'timestamp',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('incoming_time'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'clue_level' => array(
                        'name' => 'clue_level',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '线索级别',
//                         'dbType' => "varchar(25)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '25',
                        'scale' => '',
                        'size' => '25',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('clue_level'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'clue_category' => array(
                        'name' => 'clue_category',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '线索类别',
//                         'dbType' => "varchar(25)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '25',
                        'scale' => '',
                        'size' => '25',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('clue_category'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'clue_source' => array(
                        'name' => 'clue_source',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '线索来源',
//                         'dbType' => "varchar(100)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '100',
                        'scale' => '',
                        'size' => '100',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('clue_source'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'letter_number' => array(
                        'name' => 'letter_number',
                        'allowNull' => false,
//                         'autoIncrement' => false,
//                         'comment' => '信件编号',
//                         'dbType' => "varchar(25)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '25',
                        'scale' => '',
                        'size' => '25',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('letter_number'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'signature' => array(
                        'name' => 'signature',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '署名情况',
//                         'dbType' => "varchar(500)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '500',
                        'scale' => '',
                        'size' => '500',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('signature'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'leader_instructions' => array(
                        'name' => 'leader_instructions',
                        'allowNull' => false,
//                         'autoIncrement' => false,
//                         'comment' => '领导批示',
//                         'dbType' => "varchar(25)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '25',
                        'scale' => '',
                        'size' => '25',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('leader_instructions'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'respondent_unit' => array(
                        'name' => 'respondent_unit',
                        'allowNull' => false,
//                         'autoIncrement' => false,
//                         'comment' => '被反映人（单位）',
//                         'dbType' => "varchar(25)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '25',
                        'scale' => '',
                        'size' => '25',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('respondent_unit'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'duty_job' => array(
                        'name' => 'duty_job',
                        'allowNull' => false,
//                         'autoIncrement' => false,
//                         'comment' => '职务',
//                         'dbType' => "varchar(25)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '25',
                        'scale' => '',
                        'size' => '25',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('duty_job'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'rank_job' => array(
                        'name' => 'rank_job',
                        'allowNull' => false,
//                         'autoIncrement' => false,
//                         'comment' => '职级',
//                         'dbType' => "varchar(25)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '25',
                        'scale' => '',
                        'size' => '25',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('rank_job'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'main_issues' => array(
                        'name' => 'main_issues',
                        'allowNull' => false,
//                         'autoIncrement' => false,
//                         'comment' => '反映的主要问题',
//                         'dbType' => "varchar(500)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '500',
                        'scale' => '',
                        'size' => '500',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('main_issues'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'related_unit' => array(
                        'name' => 'related_unit',
                        'allowNull' => false,
//                         'autoIncrement' => false,
//                         'comment' => '涉及单位',
//                         'dbType' => "varchar(100)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '100',
                        'scale' => '',
                        'size' => '100',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('related_unit'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'heavy_cases' => array(
                        'name' => 'heavy_cases',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '重件情况',
//                         'dbType' => "varchar(500)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '500',
                        'scale' => '',
                        'size' => '500',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('heavy_cases'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'date_receipt' => array(
                        'name' => 'date_receipt',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '接到日期',
//                         'dbType' => "date",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '',
                        'scale' => '',
                        'size' => '',
                        'type' => 'date',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('date_receipt'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'transfer_organ' => array(
                        'name' => 'transfer_organ',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '处置方式',
//                         'dbType' => "varchar(25)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '25',
                        'scale' => '',
                        'size' => '25',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('transfer_organ'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'results' => array(
                        'name' => 'results',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '要结果情况',
//                         'dbType' => "varchar(500)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '500',
                        'scale' => '',
                        'size' => '500',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('results'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'supervisory_leadership' => array(
                        'name' => 'supervisory_leadership',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '督办领导',
//                         'dbType' => "varchar(25)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '25',
                        'scale' => '',
                        'size' => '25',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('supervisory_leadership'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'host_department' => array(
                        'name' => 'host_department',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '办理科室',
//                         'dbType' => "varchar(25)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '25',
                        'scale' => '',
                        'size' => '25',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('host_department'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'progress_case' => array(
                        'name' => 'progress_case',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '案件进度',
//                         'dbType' => "varchar(25)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '25',
                        'scale' => '',
                        'size' => '25',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('progress_case'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'investigation_disposal' => array(
                        'name' => 'investigation_disposal',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '查处情况',
//                         'dbType' => "varchar(500)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '500',
                        'scale' => '',
                        'size' => '500',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('investigation_disposal'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'remarks' => array(
                        'name' => 'remarks',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '备注',
//                         'dbType' => "varchar(500)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '500',
                        'scale' => '',
                        'size' => '500',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('remarks'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'number_disposals' => array(
                        'name' => 'number_disposals',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '处分人数',
//                         'dbType' => "tinyint(3)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'integer',
                        'precision' => '3',
                        'scale' => '',
                        'size' => '3',
                        'type' => 'tinyint',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('number_disposals'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'organizations_number' => array(
                        'name' => 'organizations_number',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '问题属性',
//                         'dbType' => "varchar(100)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '100',
                        'scale' => '',
                        'size' => '100',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('organizations_number'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'first_form' => array(
                        'name' => 'first_form',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '第一种形态',
//                         'dbType' => "varchar(25)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '25',
                        'scale' => '',
                        'size' => '25',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('first_form'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'second_form' => array(
                        'name' => 'second_form',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '第二种形态',
//                         'dbType' => "varchar(25)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '25',
                        'scale' => '',
                        'size' => '25',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('second_form'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'third_form' => array(
                        'name' => 'third_form',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '第三种形态',
//                         'dbType' => "varchar(25)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '25',
                        'scale' => '',
                        'size' => '25',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('third_form'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'fourth_form' => array(
                        'name' => 'fourth_form',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '第四种形态',
//                         'dbType' => "varchar(25)",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '25',
                        'scale' => '',
                        'size' => '25',
                        'type' => 'string',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('fourth_form'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'approval_time' => array(
                        'name' => 'approval_time',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '审批时间',
//                         'dbType' => "date",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '',
                        'scale' => '',
                        'size' => '',
                        'type' => 'date',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('approval_time'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'approval_status' => array(
                        'name' => 'approval_status',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '审批状态',
//                         'dbType' => "int(1)",
                        'defaultValue' => '0',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'integer',
                        'precision' => '1',
                        'scale' => '',
                        'size' => '1',
                        'type' => 'integer',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('approval_status'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),

            'is_thread_disposal' => array(
                'name' => 'is_thread_disposal',
                'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '作为线索处置',
//                         'dbType' => "varchar(25)",
                'defaultValue' => '',
                'enumValues' => null,
                'isPrimaryKey' => false,
                'phpType' => 'string',
                'precision' => '25',
                'scale' => '',
                'size' => '25',
                'type' => 'string',
                'unsigned' => false,
                'label'=>$this->getAttributeLabel('is_thread_disposal'),
                'inputType' => 'text',
                'isEdit' => true,
                'isSearch' => false,
                'isDisplay' => true,
                'isSort' => true,
//                         'udc'=>'',
            ),

            'disposal_method' => array(
                'name' => 'disposal_method',
                'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '处置方式',
//                         'dbType' => "varchar(25)",
                'defaultValue' => '',
                'enumValues' => null,
                'isPrimaryKey' => false,
                'phpType' => 'string',
                'precision' => '25',
                'scale' => '',
                'size' => '25',
                'type' => 'string',
                'unsigned' => false,
                'label'=>$this->getAttributeLabel('disposal_method'),
                'inputType' => 'text',
                'isEdit' => true,
                'isSearch' => false,
                'isDisplay' => true,
                'isSort' => true,
//                         'udc'=>'',
            ),

            'volume_number' => array(
                'name' => 'volume_number',
                'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '卷本数',
//                         'dbType' => "int(1)",
                'defaultValue' => '0',
                'enumValues' => null,
                'isPrimaryKey' => false,
                'phpType' => 'integer',
                'precision' => '3',
                'scale' => '',
                'size' => '3',
                'type' => 'integer',
                'unsigned' => false,
                'label'=>$this->getAttributeLabel('volume_number'),
                'inputType' => 'text',
                'isEdit' => true,
                'isSearch' => false,
                'isDisplay' => true,
                'isSort' => true,
//                         'udc'=>'',
            ),

            'id_card' => array(
                'name' => 'id_card',
                'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '身份证号',
//                         'dbType' => "varchar(25)",
                'defaultValue' => '',
                'enumValues' => null,
                'isPrimaryKey' => false,
                'phpType' => 'string',
                'precision' => '18',
                'scale' => '',
                'size' => '18',
                'type' => 'string',
                'unsigned' => false,
                'label'=>$this->getAttributeLabel('id_card'),
                'inputType' => 'text',
                'isEdit' => true,
                'isSearch' => false,
                'isDisplay' => true,
                'isSort' => true,
//                         'udc'=>'',
            ),

            'disposal_year' => array(
                'name' => 'disposal_year',
                'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '处置年份',
//                         'dbType' => "date",
                'defaultValue' => '',
                'enumValues' => null,
                'isPrimaryKey' => false,
                'phpType' => 'string',
                'precision' => '',
                'scale' => '',
                'size' => '',
                'type' => 'date',
                'unsigned' => false,
                'label'=>$this->getAttributeLabel('disposal_year'),
                'inputType' => 'text',
                'isEdit' => true,
                'isSearch' => false,
                'isDisplay' => true,
                'isSort' => true,
//                         'udc'=>'',
            ),

            'del_status' => array(
                        'name' => 'del_status',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '删除状态',
//                         'dbType' => "int(1)",
                        'defaultValue' => '0',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'integer',
                        'precision' => '1',
                        'scale' => '',
                        'size' => '1',
                        'type' => 'integer',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('del_status'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'create_date' => array(
                        'name' => 'create_date',
                        'allowNull' => false,
//                         'autoIncrement' => false,
//                         'comment' => '创建时间',
//                         'dbType' => "timestamp",
                        'defaultValue' => 'CURRENT_TIMESTAMP',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '',
                        'scale' => '',
                        'size' => '',
                        'type' => 'timestamp',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('create_date'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		'update_time' => array(
                        'name' => 'update_time',
                        'allowNull' => true,
//                         'autoIncrement' => false,
//                         'comment' => '更新时间',
//                         'dbType' => "timestamp",
                        'defaultValue' => '',
                        'enumValues' => null,
                        'isPrimaryKey' => false,
                        'phpType' => 'string',
                        'precision' => '',
                        'scale' => '',
                        'size' => '',
                        'type' => 'timestamp',
                        'unsigned' => false,
                        'label'=>$this->getAttributeLabel('update_time'),
                        'inputType' => 'text',
                        'isEdit' => true,
                        'isSearch' => false,
                        'isDisplay' => true,
                        'isSort' => true,
//                         'udc'=>'',
                    ),
		        );
        
    }
 
}
